// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC74-6FecqidEh5F9v4e_AVHioqEofZUk',
    appId: '1:440110607280:web:d4e324baf2ce01ce520475',
    messagingSenderId: '440110607280',
    projectId: 'pharmanoti',
    authDomain: 'pharmanoti.firebaseapp.com',
    storageBucket: 'pharmanoti.appspot.com',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOENscdjmKb5zLiWmCZbvSeF9uDPHM44k',
    appId: '1:440110607280:android:5c7f338bcdf1d04e520475',
    messagingSenderId: '440110607280',
    projectId: 'pharmanoti',
    storageBucket: 'pharmanoti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkqU8F3ICbR65-zDLcmp6skqbLQh5gGs',
    appId: '1:440110607280:ios:082bd2181fd0504c520475',
    messagingSenderId: '440110607280',
    projectId: 'pharmanoti',
    storageBucket: 'pharmanoti.appspot.com',
    iosBundleId: 'com.example.pharma',
  );
}
